### ISSUE TITLE
ocrpdf fails with error message from pdfimages

### ISSUE THREAD

**Issue by Ejneafsey** [maxim2266/OCRPDF#1]
I compiled ocrpdf on linux ubuntu 14.04 but it won't process a pdf file.  It issues an error message from pdfimages

eneafse:~/Downloads$ ocrpdf declasspart4.pdf 
ERROR: pdfimages version 3.04
Copyright 1996-2014 Glyph & Cog, LLC
Usage: pdfimages [options] <PDF-file> <image-root>
  -f <int>       : first page to convert
  -l <int>       : last page to convert
  -j             : write JPEG images as JPEG files
  -opw <string>  : owner password (for encrypted files)
  -upw <string>  : user password (for encrypted files)
  -q             : don't print any messages or errors
  -cfg <string>  : configuration file to use in place of .xpdfrc
  -v             : print copyright and version info
  -h             : print usage information
  -help          : print usage information
  --help         : print usage information
  -?             : print usage information

Thanks.

E.J. Neafsey

**Comment by maxim2266** [comment]
I did not test the tool on Ubuntu 14.04 because I do not have it at the moment. From the output it looks like your version of 'pdfimages' tool does not have '-tiff' option.
